# Generated by Django 5.1 on 2024-08-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_steps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='Step',
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name_plural': 'Steps'},
        ),
    ]
