# Generated by Django 5.1 on 2024-08-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_rename_steps_step_alter_step_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.AddField(
            model_name='post',
            name='characteristics',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.TextField(default=1),
        ),
    ]
