# Generated by Django 5.1 on 2024-08-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_delete_step_post_characteristics_post_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='post',
            name='code',
        ),
    ]
