# Generated by Django 5.1 on 2024-08-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
