# Generated by Django 5.1 on 2024-08-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_comment_email_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=10, max_length=255),
            preserve_default=False,
        ),
    ]
