# Generated by Django 5.1 on 2024-08-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='active', max_length=10),
        ),
    ]
